### ISSUE TITLE
INSERT prepared statement fails with accented chars

### ISSUE THREAD

**Issue by fvanzeveren** [Siskin-framework/Rebol-SQLite#1]
Hi Oldes
A few weeks ago (actually, I think it was 2 months ago), I wrote that I was going to test and use Rebol3-SQLite quite extensively and would post issues I encounters.
Voilà, here is the first one, very annoying for non english users :)

I have detected and tested this issue on Haiku Beta 4.

```
print "Trying to import SQLite extension..."
;; make sure that we load a fresh extension
try [system/modules/sqlite: none]
sqlite: import 'sqlite

recycle/torture

with sqlite [
	db: open %test.db

	;- The folowwing statement works fine
	exec db {
		BEGIN TRANSACTION;
		DROP TABLE IF EXISTS Contacts;
		CREATE TABLE Contacts (
			email TEXT PRIMARY KEY,
			first_name TEXT NOT NULL,
			last_name TEXT NOT NULL
		);
		INSERT INTO "Contacts" VALUES(
			'oceane.pacome@corporate.com',
			'Océane', 'Pacôme'
		);
		COMMIT;

	}
	;- The following statement does not work:
	;- the persisted value for first_name is "O" and 
	;- the persisted value for last_name is "P"
	stmt: prepare db "INSERT INTO Contacts VALUES(?,?,?);"
	rec: step/with stmt ["o2.pacome@corporate.com" "Océane Jr" "Pacôme"]
	
	exec db "SELECT * FROM Contacts"
	close db
	shutdown
]

```
I hope you will be able to fix this soon.

Regards

François

**Comment by Oldes** [comment]
Fixed in the commit above.

Note that in the `exec` command there is just a plain `printf` from C, so it may not display output correctly in the console. To have Rebol data from the query for the test I used.

```rebol
	select-stmt: prepare db "SELECT * FROM Contacts"
	probe step select-stmt
```

Also note that current implementation is just a low-level code.. there is a missing `sqlite` scheme, which should hide this statement preparation. My goal is to have something like:
```rebol
db: open sqlite:test.db
insert db "SELECT * FROM Contacts" ;= will prepare the statement
read db                            ;= will get all data from the statement
close db
```
Or maybe just `write` instead of the `insert`+`read` combo. Ideas are welcome.

**Comment by Oldes** [comment]
Also you may want to comment out the `recycle/torture` line... it is used just in the CI test to find possible GC issues... you should not use it normally.

**Comment by Oldes** [comment]
@fvanzeveren here is initial implementation of the SQLite scheme (just as a script, not part of the extension).
https://github.com/Siskin-framework/Rebol-SQLite/blob/main/sqlite-scheme.r3

I would appreciate any idea how to improve it... in issues or in discussions...
What it does not handle yet are queries with separated data.. like yours:
```rebol
stmt: prepare db "INSERT INTO Contacts VALUES(?,?,?);"
step/with stmt ["o2.pacome@corporate.com" "Océane Jr" "Pacôme"]
```
because I am not sure, what would be the best way, how to solve it in the scheme with limited Rebol actions.

**Comment by fvanzeveren** [comment]
@Oldes 
Thank you for your quick fix! It is now working for non-english speakers ;)
Regarding the SQLite Scheme, I did sth similar. I wrote a wrapper script to hide the "complexity" and verbosity of the current "raw level" code. But I also had in mind to immunize the main rebol application from a change in database engine, hoping that in the future we would benefit from MySQL/MariaDB library.
You can find the current version of the script [here](http://www.kis.ovh/public/sqlite.txt).
Note the caching of db connections and prepared statements which allow not to bother about handles in the main code.

A typical use is:
```
do %sqlite.r3
sql: copy {SELECT * FROM MyTable}
probe rec: sql-run %mydbname.db sql
while [not none? rec] [
  probe rec: sql-next sql
]
sql-shutdown
```
Hope it helps!

Regards 

François

**Comment by Oldes** [comment]
Maybe you could join us [here](https://app.element.io/#/room/#Rebol3:gitter.im).
